Repository GSA/sam-design-system, pull requests merged in 2020-12, with the labels that each got.

#436 Fix subheader demos and searchbar blur
  libs/documentation/src/lib/components/subheader/demos/search-sub-pages/subheader-search-sub-pages.component.html
  libs/documentation/src/lib/components/subheader/demos/search-sub-pages/subheader-search-sub-pages.component.ts
  libs/documentation/src/lib/components/subheader/demos/search-sub-pages/subheader-search-sub-pages.module.ts
  libs/documentation/src/lib/components/subheader/demos/search/subheader-search.component.html
  libs/documentation/src/lib/components/subheader/demos/search/subheader-search.component.ts
  libs/documentation/src/lib/components/subheader/demos/search/subheader-search.module.ts
  libs/documentation/src/lib/components/subheader/demos/tier-2-workspace/subheader-tier-2-workspace.component.html
  libs/documentation/src/lib/components/subheader/demos/tier-2-workspace/subheader-tier-2-workspace.module.ts
  libs/packages/components/src/lib/search/search.component.html
  libs/packages/components/src/lib/search/search.component.ts
  libs/packages/components/src/lib/search/search.spec.ts
Labels: bugfix

#439 IAE-4429 Update search model writing behavior
  libs/documentation/src/lib/components/formly/search/demos/submit/search-handle-submit.component.html
  libs/documentation/src/lib/components/formly/search/demos/submit/search-handle-submit.component.ts
  libs/documentation/src/lib/components/formly/search/demos/submit/search-handle-submit.module.ts
  libs/documentation/src/lib/components/formly/search/search.module.ts
  libs/documentation/src/lib/components/search/demos/basic/search-basic.component.html
  libs/documentation/src/lib/components/search/demos/basic/search-basic.component.ts
  libs/packages/components/src/lib/search/search.component.html
  libs/packages/components/src/lib/search/search.component.ts
  libs/packages/components/src/lib/search/search.spec.ts
  libs/packages/sam-formly/src/lib/formly/types/search.ts
Labels: breaking

#448 IAE-44578 Add check to ensure changeDetectorRef not destroyed
  libs/packages/sam-formly/src/lib/formly/types/multicheckbox.ts
Labels: bugfix

#449 Update search component to input configurations through searchSettings
  libs/documentation/src/lib/components/search/demos/basic/search-basic.component.html
  libs/documentation/src/lib/components/search/demos/basic/search-basic.component.scss
  libs/documentation/src/lib/components/search/demos/basic/search-basic.component.ts
  libs/documentation/src/lib/components/search/demos/optional/search-optional.component.html
  libs/documentation/src/lib/components/subheader/demos/search-sub-pages/subheader-search-sub-pages.component.html
  libs/documentation/src/lib/components/subheader/demos/search-sub-pages/subheader-search-sub-pages.component.ts
  libs/documentation/src/lib/components/subheader/demos/search-sub-pages/subheader-search-sub-pages.module.ts
  libs/documentation/src/lib/components/subheader/demos/search/subheader-search.component.html
  libs/documentation/src/lib/components/subheader/demos/search/subheader-search.component.ts
  libs/documentation/src/lib/components/subheader/demos/search/subheader-search.module.ts
  libs/documentation/src/lib/components/subheader/demos/tier-2-workspace/subheader-tier-2-workspace.component.html
  libs/documentation/src/lib/components/subheader/demos/tier-2-workspace/subheader-tier-2-workspace.component.ts
  libs/documentation/src/lib/components/subheader/demos/tier-2-workspace/subheader-tier-2-workspace.module.ts
  libs/packages/components/src/lib/search/search.component.html
  libs/packages/components/src/lib/search/search.component.ts
Labels: breaking

#456 Remove duplicate export of truncate-text library
  libs/packages/components/src/lib/public-api.ts
Labels: bugfix

#466 IAE-43995 Add Inactive Filter Value Option
  libs/documentation/src/lib/components/filters/demos/showInactiveFilterValues/filters-showInactiveFilterValues.component.html
  libs/documentation/src/lib/components/filters/demos/showInactiveFilterValues/filters-showInactiveFilterValues.component.ts
  libs/documentation/src/lib/components/filters/demos/showInactiveFilterValues/filters-showInactiveFilterValues.module.ts
  libs/documentation/src/lib/components/filters/filters.module.ts
  libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/advanced-filters.component.ts
  libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/sds-advanced-filters.service.spec.ts
  libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/sds-advanced-filters.service.ts
  libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.html
  libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
  libs/packages/sam-formly/src/lib/formly-reset/formly-reset.component.spec.ts
  libs/packages/sam-formly/src/lib/formly/types/checkbox.ts
  package-lock.json
  package.json
Labels: enhancement
