Repository GSA/sam-design-system, pull requests merged in 2020-08, with the labels that each got.

#311 Multi checkbox css updated in sam-style version 0.0.79
  libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/sds-advanced-filters.service.ts
  libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
  libs/packages/sam-formly/src/lib/formly/types/multicheckbox.scss
  libs/packages/sam-formly/src/lib/formly/types/multicheckbox.ts
  package-lock.json
  package.json
Labels: enhancement

#318 Updated autocomplete to support 3 level groupping
  libs/documentation/src/lib/components/autocomplete/demos/group/service/autocomplete-sample.service.ts
  libs/documentation/src/lib/components/autocomplete/demos/group/service/datachildgroup.ts
  libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html
  libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.spec.ts
  libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts
Labels: enhancement

#287 Filter by domain 33314
  libs/component-sample/src/lib/feature/side-navigation-sample/side-navigation-sample.component.html
  libs/component-sample/src/lib/feature/side-navigation-sample/side-navigation-sample.component.ts
  libs/documentation/src/lib/components/sidenavigation/demos/basic/sidenavigation-basic.component.html
  libs/documentation/src/lib/components/sidenavigation/demos/basic/sidenavigation-basic.component.scss
  libs/documentation/src/lib/components/sidenavigation/demos/basic/sidenavigation-basic.component.ts
  libs/documentation/src/lib/components/sidenavigation/demos/basic/sidenavigation-basic.module.ts
  libs/documentation/src/lib/components/sidenavigation/demos/optional/navigate.config.ts
  libs/documentation/src/lib/components/sidenavigation/demos/optional/sidenavigation-optional.component.html
  libs/documentation/src/lib/components/sidenavigation/demos/optional/sidenavigation-optional.component.ts
  libs/documentation/src/lib/components/sidenavigation/sidenavigation.module.ts
  libs/packages/components/src/lib/side-navigation/side-navigation.component.html
  libs/packages/components/src/lib/side-navigation/side-navigation.component.spec.ts
  libs/packages/components/src/lib/side-navigation/side-navigation.component.ts
Labels: feat

#324 bugfix(multicheckbox): styling fix
  libs/packages/sam-formly/src/lib/formly/types/multicheckbox.html
Labels: bugfix

#329 Sam styles@v0.0.81
  libs/documentation/src/lib/pages/layout/layout.component.html
  package-lock.json
  package.json
Labels: Dependency

#319 Mat Table
  apps/sam-design-system-site/src/app/app.component.html
  libs/documentation/src/lib/apidoc/index.ts
  libs/documentation/src/lib/apidoc/material/documentation.json
  libs/documentation/src/lib/apidoc/material/material.ts
  libs/documentation/src/lib/components/table/demos/table-basic/table-basic.component.html
  libs/documentation/src/lib/components/table/demos/table-basic/table-basic.component.ts
  libs/documentation/src/lib/components/table/demos/table-basic/table-basic.module.ts
  libs/documentation/src/lib/components/table/demos/table-borderless/table-borderless.component.html
  libs/documentation/src/lib/components/table/demos/table-borderless/table-borderless.component.ts
  libs/documentation/src/lib/components/table/demos/table-borderless/table-borderless.module.ts
  libs/documentation/src/lib/components/table/demos/table-expandable-row/table-expandable-row.component.html
  libs/documentation/src/lib/components/table/demos/table-expandable-row/table-expandable-row.component.ts
  libs/documentation/src/lib/components/table/demos/table-expandable-row/table-expandable-row.module.ts
  libs/documentation/src/lib/components/table/demos/table-sort/table-sort.component.html
  libs/documentation/src/lib/components/table/demos/table-sort/table-sort.component.ts
  libs/documentation/src/lib/components/table/demos/table-sort/table-sort.module.ts
  libs/documentation/src/lib/components/table/demos/table-sticky-column/table-sticky-column.component.html
  libs/documentation/src/lib/components/table/demos/table-sticky-column/table-sticky-column.component.ts
  libs/documentation/src/lib/components/table/demos/table-sticky-column/table-sticky-column.module.ts
  libs/documentation/src/lib/components/table/demos/table-sticky-header/table-sticky-header.component.html
  libs/documentation/src/lib/components/table/demos/table-sticky-header/table-sticky-header.component.ts
  libs/documentation/src/lib/components/table/demos/table-sticky-header/table-sticky-header.module.ts
  libs/documentation/src/lib/components/table/opening.md
  libs/documentation/src/lib/components/table/table.module.ts
  libs/documentation/src/lib/documentation.module.ts
  libs/documentation/src/lib/pages/introduction/introduction.component.html
  libs/documentation/src/lib/pages/introduction/introduction.component.ts
  libs/packages/sam-material-extensions/src/lib/packages-sam-material-extensions.module.spec.ts
  libs/packages/sam-material-extensions/src/lib/packages-sam-material-extensions.module.ts
  libs/packages/sam-material-extensions/src/lib/public-api.ts
  libs/packages/sam-material-extensions/src/lib/table/models/table-column-settings.model.ts
  libs/packages/sam-material-extensions/src/lib/table/models/table-settings.model.ts
  libs/packages/sam-material-extensions/src/lib/table/table.component.html
  libs/packages/sam-material-extensions/src/lib/table/table.component.scss
  libs/packages/sam-material-extensions/src/lib/table/table.component.spec.ts
  libs/packages/sam-material-extensions/src/lib/table/table.component.ts
  libs/packages/sam-material-extensions/src/lib/table/table.module.ts
  libs/packages/sam-material-extensions/tslint.json
  package.json
Labels: feat

#321 add navbar title
  libs/component-sample/src/lib/feature/subheader-sample/subheader-sample.component.html
  libs/documentation/src/lib/components/subheader/demos/basic/subheader-basic.component.html
Labels: bugfix

#332 Formly dialog
  apps/sam-design-system-site/src/app/app.component.html
  libs/documentation/src/lib/apidoc/components/components.ts
  libs/documentation/src/lib/apidoc/components/documentation.json
  libs/documentation/src/lib/apidoc/formly/documentation.json
  libs/documentation/src/lib/apidoc/formly/formly.ts
  libs/documentation/src/lib/components/download/demos/download/download.component.html
  libs/documentation/src/lib/components/download/demos/download/download.component.ts
  libs/documentation/src/lib/components/download/demos/download/download.module.ts
  libs/documentation/src/lib/components/download/demos/formly-modal/formly-modal.component.html
  libs/documentation/src/lib/components/download/demos/formly-modal/formly-modal.component.ts
  libs/documentation/src/lib/components/download/demos/formly-modal/formly-modal.module.ts
  libs/documentation/src/lib/components/download/download.module.ts
  libs/documentation/src/lib/components/filters/demos/config/filter-config.module.ts
  libs/documentation/src/lib/components/subheader/demos/basic/subheader-basic.component.html
  libs/documentation/src/lib/components/subheader/demos/basic/subheader-basic.component.ts
  libs/documentation/src/lib/components/subheader/demos/basic/subheader-basic.module.ts
  libs/documentation/src/lib/documentation.module.ts
  libs/packages/sam-formly/src/lib/formly-dialog/formly-dialog-data.model.ts
  libs/packages/sam-formly/src/lib/formly-dialog/formly-dialog.component.spec.ts
  libs/packages/sam-formly/src/lib/formly-dialog/formly-dialog.component.ts
  libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/advanced-filters.component.spec.ts
  libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/advanced-filters.component.ts
  libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/sds-advanced-filters.service.spec.ts
  libs/packages/sam-formly/src/lib/formly/formly.config.ts
  libs/packages/sam-formly/src/lib/formly/types/fileinfo.ts
  tsconfig.json
Labels: enhancement

#333 Hide expression changes
  libs/documentation/src/lib/components/filters/demos/config/fields.ts
  libs/documentation/src/lib/components/filters/demos/config/filter-config.component.ts
  libs/documentation/src/lib/components/filters/demos/hideexpression/filters-hideexpression.component.html
  libs/documentation/src/lib/components/filters/demos/hideexpression/filters-hideexpression.component.ts
  libs/documentation/src/lib/components/filters/demos/hideexpression/filters-hideexpression.module.ts
  libs/documentation/src/lib/components/filters/filters.module.ts
  libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.spec.ts
  libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
Labels: enhancement
