Repository GSA/sam-design-system, pull requests merged in 2020-01, with the labels that each got.

#135 Update CODEOWNERS
  CODEOWNERS
Labels: gren-ignore

#134 IE 11 fixes
  apps/sam-design-system-site/browserslist
  apps/sam-design-system-site/src/styles.scss
  libs/component-sample/src/lib/feature/search-result-list-sample/search-result-list-sample-data.component.html
  libs/layout-sample/src/lib/feature/search-list/search-list-sample.component.html
  libs/layout-sample/src/lib/ui/search-result-list-sample-data/search-result-list-sample-data.component.html
  libs/packages/components/src/lib/pagination/pagination.component.html
Labels: bugfix

#140 29173 dual record display - v2
  libs/component-sample/src/lib/feature/search-result-list-sample/dual-display.component.html
  libs/component-sample/src/lib/feature/search-result-list-sample/dual-display.component.ts
  libs/component-sample/src/lib/feature/search-result-list-sample/search-result-list-sample-data.component.html
  libs/component-sample/src/lib/feature/search-result-list-sample/search-result-list-sample.component.html
  libs/component-sample/src/lib/feature/search-result-list-sample/search-result-list-sample.component.ts
  libs/component-sample/src/lib/feature/search-result-list-sample/search-result-list-sample.module.ts
Labels: enhancement
