Repository GSA/sam-design-system, pull requests merged in 2021-09, with the labels that each got.

#809 Add output event on sortfield change and on reset click
  libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
  libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.html
  libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
  libs/packages/sam-formly/src/lib/formly-reset/formly-reset.component.ts
Labels: enhancement

#812 V11.0.3
  libs/packages/components/package.json
  libs/packages/layouts/package.json
  libs/packages/sam-formly/package.json
  libs/packages/sam-material-extensions/package.json
  package-lock.json
  package.json
Labels: Dependency

#813 Remove nrwl
  README.md
  angular.json
  decorate-angular-cli.js
  jest.config.js
  nx.json
  package-lock.json
  package.json
  tslint.json
Labels: Dependency

#814 Add demo for horizontal layout
  libs/documentation/src/lib/components/filters/demos/horizontal-filter/horizontal-filter.component.html
  libs/documentation/src/lib/components/filters/demos/horizontal-filter/horizontal-filter.component.ts
  libs/documentation/src/lib/components/filters/demos/horizontal-layout/horizontal-layout.component.html
  libs/documentation/src/lib/components/filters/demos/horizontal-layout/horizontal-layout.component.ts
  libs/documentation/src/lib/components/filters/demos/horizontal-layout/horizontal-layout.module.ts
  libs/documentation/src/lib/components/filters/filters.module.ts
  libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.scss
  libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts
  libs/packages/sam-formly/src/lib/formly/wrappers/group.wrapper.ts
  libs/packages/sam-formly/src/lib/formly/wrappers/label.wrapper.ts
Labels: Documentation

#815 IAE-56716: Update ngx-uswds-icons version to 0.0.7
  package-lock.json
  package.json
Labels: bugfix

#821 Add display modifier function for autocomplete chips
  libs/documentation/src/lib/pages/layout/filter.service.ts
  libs/documentation/src/lib/pages/layout/layout-responsive/layout-responsive.component.ts
  libs/documentation/src/lib/pages/layout/layout.component.ts
  libs/packages/components/src/lib/autocomplete/autocomplete.component.ts
  libs/packages/components/src/lib/autocomplete/models/SDSAutocompletelConfiguration.model.ts
  libs/packages/components/src/lib/selected-result/models/SDSSelectedResultConfiguration.ts
  libs/packages/components/src/lib/selected-result/selected-result.component.html
  libs/packages/components/src/lib/selected-result/selected-result.component.ts
Labels: enhancement

#825 Remove unnecessary event from hostlistener
  libs/packages/components/src/lib/tooltip/tooltip.directive.ts
Labels: bugfix

#826 Lock stackblitz demo at 11.0.3
  misc/generate-stackblitzes.ts
Labels: bugfix

#827 Resolve styling issue for stackblitz
  misc/generate-stackblitzes.ts
Labels: bugfix
