Repository GSA/sam-design-system, pull requests merged in 2021-08, with the labels that each got.

#765 Step indicator directives
  libs/documentation/src/lib/components/formly-stepper/demos/uswds-stepper/uswds-custom-stepper.component.html
  libs/documentation/src/lib/components/formly-stepper/demos/uswds-stepper/uswds-custom-stepper.component.ts
  libs/documentation/src/lib/components/formly-stepper/demos/uswds-stepper/uswds-stepper.component.html
  libs/documentation/src/lib/components/formly-stepper/demos/uswds-stepper/uswds-stepper.component.ts
  libs/documentation/src/lib/components/formly-stepper/demos/uswds-stepper/uswds-stepper.module.ts
  libs/documentation/src/lib/components/formly-stepper/formly-stepper.module.ts
  libs/packages/sam-formly/src/lib/formly-stepper/sds-step-buttons.ts
  libs/packages/sam-formly/src/lib/formly-stepper/sds-stepper.module.ts
  libs/packages/sam-formly/src/lib/formly-stepper/sds-stepper.ts
  package-lock.json
  package.json
Labels: enhancement

#766 Add tabs formly type
  apps/sam-design-system-site/src/app/app.component.html
  apps/sam-design-system-site/src/base-documentation.scss
  libs/documentation/src/lib/components/formly-tabs/demos/basic/formly-tabs-basic.component.html
  libs/documentation/src/lib/components/formly-tabs/demos/basic/formly-tabs-basic.component.ts
  libs/documentation/src/lib/components/formly-tabs/demos/basic/formly-tabs-basic.module.ts
  libs/documentation/src/lib/components/formly-tabs/formly-tabs.module.ts
  libs/documentation/src/lib/documentation.module.ts
  libs/documentation/src/lib/pages/layout/data.service.ts
  libs/documentation/src/lib/pages/layout/filter.service.ts
  libs/packages/components/src/lib/tabs/tabs.component.scss
  libs/packages/components/src/lib/tabs/tabs.component.ts
  libs/packages/sam-formly/src/lib/formly/formly.config.ts
  libs/packages/sam-formly/src/lib/formly/formly.module.ts
  libs/packages/sam-formly/src/lib/formly/models/formly-types.ts
  libs/packages/sam-formly/src/lib/formly/types/tabs.spec.ts
  libs/packages/sam-formly/src/lib/formly/types/tabs.ts
Labels: enhancement

#767 Update version to 10.0.36
  libs/packages/components/package.json
  libs/packages/layouts/package.json
  libs/packages/sam-formly/package.json
  libs/packages/sam-material-extensions/package.json
  package-lock.json
  package.json
Labels: Dependency

#773 Update sam-styles version to 0.116
  package-lock.json
  package.json
Labels: Dependency

#783 Angular 11 update
  angular.json
  apps/sam-design-system-site/src/app/app.component.spec.ts
  apps/sam-design-system-site/src/app/app.module.ts
  libs/documentation/src/lib/documentation.module.spec.ts
  libs/packages/components/package.json
  libs/packages/components/src/lib/accordion/accordion-item.component.spec.ts
  libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.spec.ts
  libs/packages/components/src/lib/autocomplete/autocomplete.component.spec.ts
  libs/packages/components/src/lib/click-outside/click-outside.spec.ts
  libs/packages/components/src/lib/icon/icon.component.spec.ts
  libs/packages/components/src/lib/menu/menu.component.spec.ts
  libs/packages/components/src/lib/pagination/pagination.component.spec.ts
  libs/packages/components/src/lib/search-result-list/search-result-list.component.spec.ts
  libs/packages/components/src/lib/search/search.spec.ts
  libs/packages/components/src/lib/selected-result/selected-result.component.spec.ts
  libs/packages/components/src/lib/side-navigation/side-navigation.component.spec.ts
  libs/packages/components/src/lib/tab-outside/taboutside.spec.ts
  libs/packages/components/src/lib/top-banner/top-banner.component.spec.ts
  libs/packages/components/tsconfig.lib.json
  libs/packages/components/tsconfig.lib.prod.json
  libs/packages/layouts/package.json
  libs/packages/layouts/src/lib/feature/footer/footer.component.spec.ts
  libs/packages/layouts/src/lib/feature/header/header.component.spec.ts
  libs/packages/layouts/src/lib/feature/sds-feedback/sds-feedback.component.spec.ts
  libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.spec.ts
  libs/packages/layouts/src/lib/feature/side-toolbar/side-toolbar.component.spec.ts
  libs/packages/layouts/src/lib/feature/system-alert/system-alert.component.spec.ts
  libs/packages/layouts/src/lib/packages-layouts.module.spec.ts
  libs/packages/layouts/tsconfig.lib.json
  libs/packages/layouts/tsconfig.lib.prod.json
  libs/packages/sam-formly/package.json
  libs/packages/sam-formly/src/lib/formly-dialog/formly-dialog.component.spec.ts
  libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/advanced-filters.component.spec.ts
  libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/sds-advanced-filters.service.spec.ts
  libs/packages/sam-formly/src/lib/formly-reset/formly-reset.component.spec.ts
  libs/packages/sam-formly/src/lib/formly-stepper/sds-stepper.component.spec.ts
  libs/packages/sam-formly/src/lib/formly-stepper/sds-stepper.ts
  libs/packages/sam-formly/src/lib/formly/types/autocomplete.spec.ts
  libs/packages/sam-formly/src/lib/formly/types/checkbox.spec.ts
  libs/packages/sam-formly/src/lib/formly/types/datepicker.spec.ts
  libs/packages/sam-formly/src/lib/formly/types/file-input.html
  libs/packages/sam-formly/src/lib/formly/types/radio.spec.ts
  libs/packages/sam-formly/src/lib/formly/types/search.spec.ts
  libs/packages/sam-formly/src/lib/formly/types/select.spec.ts
  libs/packages/sam-formly/tsconfig.lib.json
  libs/packages/sam-formly/tsconfig.lib.prod.json
  libs/packages/sam-material-extensions/package.json
  libs/packages/sam-material-extensions/src/lib/accordion/accordion.component.spec.ts
  libs/packages/sam-material-extensions/src/lib/table/table-basic.component.spec.ts
  libs/packages/sam-material-extensions/src/lib/table/table.component.spec.ts
  libs/packages/sam-material-extensions/tsconfig.lib.json
  libs/packages/sam-material-extensions/tsconfig.lib.prod.json
  package-lock.json
  package.json
Labels: breaking, Dependency

#782 Resolve recursive navigation due to page params
  libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
Labels: bugfix

#781 Update horizontal filters
  libs/documentation/src/lib/components/filters/demos/horizontal-filter/horizontal-filter.component.html
  libs/documentation/src/lib/components/filters/demos/horizontal-filter/horizontal-filter.component.ts
  libs/documentation/src/lib/components/filters/demos/horizontal-filter/horizontal-filter.module.ts
  libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/advanced-filters.component.html
  libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/advanced-filters.component.ts
  libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/sds-advanced-filters.service.ts
  libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.html
  libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
  libs/packages/sam-formly/src/lib/formly-filters/sds-filters.module.ts
  libs/packages/sam-formly/src/lib/formly-reset/formly-reset.component.ts
  libs/packages/sam-formly/src/lib/formly/services/utils.ts
  libs/packages/sam-formly/src/lib/formly/types/daterangepicker.ts
  libs/packages/sam-formly/src/lib/formly/wrappers/group.wrapper.ts
Labels: enhancement

#784 Adding custom modal action events for submit and cancel
  libs/documentation/src/lib/components/download/demos/download/download.component.ts
  libs/documentation/src/lib/components/download/demos/formlymodal/formly-modal.component.ts
  libs/documentation/src/lib/components/subheader/demos/basic/subheader-basic-display.component.ts
  libs/documentation/src/lib/components/subheader/demos/dataentry/subheader-data-entry.component.ts
  libs/documentation/src/lib/components/subheader/demos/search-autocomplete/subheader-search-autocomplete.component.ts
  libs/documentation/src/lib/components/subheader/demos/search/subheader-search.component.ts
  libs/documentation/src/lib/components/subheader/demos/subpages/subheader-search-sub-pages.component.ts
  libs/documentation/src/lib/components/subheader/demos/workspace/subheader-tier-2-workspace.component.ts
  libs/packages/sam-formly/src/lib/formly-dialog/formly-dialog.component.spec.ts
  libs/packages/sam-formly/src/lib/formly-dialog/formly-dialog.component.ts
  libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/advanced-filters.component.ts
Labels: breaking

#786 Update modal for accepting the success type
  libs/documentation/src/lib/components/dialog/demos/alert/dialog-alert.component.ts
  libs/packages/components/src/lib/dialog/dialog-config.ts
  libs/packages/components/src/lib/dialog/dialog-container.component.html
  libs/packages/components/src/lib/dialog/dialog-container.component.ts
  package-lock.json
Labels: enhancement

#788 Prod build bug fixes
  libs/packages/sam-formly/src/lib/formly-filters/advanced-filters/advanced-filters.component.html
  libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.html
Labels: bugfix

#789 Add table for file input
  libs/documentation/src/lib/components/formly-file-input/demos/table-file-input/table-file-input.component.html
  libs/documentation/src/lib/components/formly-file-input/demos/table-file-input/table-file-input.component.ts
  libs/documentation/src/lib/pages/layout/layout.component.ts
  libs/packages/sam-formly/src/lib/formly/formly.config.ts
  libs/packages/sam-formly/src/lib/formly/formly.module.ts
  libs/packages/sam-formly/src/lib/formly/models/formly-types.ts
  libs/packages/sam-formly/src/lib/formly/types/file-input.html
  libs/packages/sam-formly/src/lib/formly/types/file-input.ts
  libs/packages/sam-formly/src/lib/formly/types/table.html
  libs/packages/sam-formly/src/lib/formly/types/table.ts
  libs/packages/sam-formly/src/lib/formly/types/tabs.ts
Labels: enhancement

#801 Update loading blocks based on demo feedback
  libs/documentation/src/lib/components/formly-stepper/demos/advanced/stepper-advanced.component.html
  libs/packages/components/src/lib/search-result-list/search-result-list.component.html
  libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.html
Labels: bugfix

#805 Refactor tabs as formly wrapper
  apps/sam-design-system-site/src/app/app.component.html
  libs/documentation/src/lib/components/formly-tabs/demos/basic/formly-tabs-basic.component.ts
  libs/documentation/src/lib/pages/layout/filter.service.ts
  libs/packages/sam-formly/src/lib/formly/formly.config.ts
  libs/packages/sam-formly/src/lib/formly/wrappers/tabs.wrapper.spec.ts
  libs/packages/sam-formly/src/lib/formly/wrappers/tabs.wrapper.ts
Labels: enhancement
