Repository GSA/sam-design-system, pull requests merged in 2021-12, with the labels that each got.

#884 Update expansion behavior for tree table
  libs/packages/components/src/lib/tree-table/tree-table.component.html
  libs/packages/components/src/lib/tree-table/tree-table.component.ts
Labels: enhancement

#816 IAE-56718: Update sidenav to include header and apply button by default
  libs/documentation/src/lib/components/sidenavigation/demos/filter-side-navigation/filter-side-navigation.component.html
  libs/documentation/src/lib/components/sidenavigation/demos/filter-side-navigation/filter-side-navigation.component.ts
  libs/documentation/src/lib/components/sidenavigation/demos/filter-side-navigation/filter-side-navigation.module.ts
  libs/documentation/src/lib/components/sidenavigation/demos/filter-side-navigation/navigation.config.ts
  libs/documentation/src/lib/components/sidenavigation/demos/links-side-navigation/links-side-navigation.component.html
  libs/documentation/src/lib/components/sidenavigation/demos/links-side-navigation/links-side-navigation.component.ts
  libs/documentation/src/lib/components/sidenavigation/demos/links-side-navigation/links-side-navigation.module.ts
  libs/documentation/src/lib/components/sidenavigation/demos/optional/navigate.config.ts
  libs/documentation/src/lib/components/sidenavigation/demos/optional/sidenavigation-optional.component.html
  libs/documentation/src/lib/components/sidenavigation/demos/optional/sidenavigation-optional.component.ts
  libs/documentation/src/lib/components/sidenavigation/sidenavigation.module.ts
  libs/packages/components/src/lib/side-navigation/side-navigation.component.html
  libs/packages/components/src/lib/side-toolbar/side-toolbar.component.html
  libs/packages/components/src/lib/side-toolbar/side-toolbar.component.scss
  libs/packages/components/src/lib/side-toolbar/side-toolbar.component.ts
  libs/packages/components/src/lib/side-toolbar/side-toolbar.module.ts
  libs/packages/layouts/src/lib/feature/side-toolbar/side-toolbar.component.html
  libs/packages/layouts/src/lib/feature/side-toolbar/side-toolbar.component.scss
  libs/packages/layouts/src/lib/feature/side-toolbar/side-toolbar.component.spec.ts
  libs/packages/layouts/src/lib/feature/side-toolbar/side-toolbar.component.ts
  libs/packages/layouts/src/lib/feature/side-toolbar/side-toolbar.module.ts
  libs/packages/layouts/src/lib/public-api.ts
  package-lock.json
  package.json
Labels: breaking

#888 Release 11.0.18
  libs/packages/components/package.json
  libs/packages/layouts/package.json
  libs/packages/sam-formly/package.json
  libs/packages/sam-material-extensions/package.json
  package-lock.json
  package.json
Labels: Dependency

#889 Accordion expansion on groupwrapper update
  libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.spec.ts
  libs/packages/sam-formly/src/lib/formly/wrappers/form-field.accordian.ts
  libs/packages/sam-formly/src/lib/formly/wrappers/group.wrapper.ts
  package-lock.json
  package.json
Labels: bugfix, breaking

#890 Update selection panel to allow fragment navigation
  apps/sam-design-system-site/src/app/app.module.ts
  libs/documentation/src/lib/components/selection-panel/demos/basic/basic-selection-panel.component.html
  libs/documentation/src/lib/components/selection-panel/demos/basic/navigation.config.ts
  libs/packages/components/src/lib/selection-panel/navigation-mode/navigation-mode.component.ts
Labels: enhancement
