Repository GSA/sam-design-system, pull requests merged in 2021-04, with the labels that each got.

#654 Update accordion css, reset filter on layout destroy, auto close responsive modal on window resize
  libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
  libs/packages/layouts/src/lib/feature/side-toolbar/side-toolbar.component.ts
  libs/packages/sam-material-extensions/src/lib/accordion/accordion.component.scss
Labels: bugfix

#668 Remove fsd from internal links exception
  libs/documentation/src/lib/components/external-link/demos/basic/external-link-basic.component.html
  libs/packages/components/src/lib/external-link/external-link.directive.ts
Labels: bugfix

#659 Update tsconfig pathing
  apps/sam-design-system-site/tsconfig.json
  libs/packages/components/tsconfig.lib.prod.json
  libs/packages/components/tsconfig.spec.json
  libs/packages/layouts/tsconfig.lib.prod.json
  libs/packages/layouts/tsconfig.spec.json
  libs/packages/sam-formly/tsconfig.lib.prod.json
  libs/packages/sam-formly/tsconfig.spec.json
  libs/packages/sam-material-extensions/tsconfig.lib.prod.json
  libs/packages/sam-material-extensions/tsconfig.spec.json
  package-lock.json
  package.json
  tsconfig.json
Labels: Dependency

#669 Add demo for accordion list in cards
  libs/documentation/src/lib/components/accordion/accordion.module.ts
  libs/documentation/src/lib/components/accordion/demos/cardlist/accordion-cardlist.component.html
  libs/documentation/src/lib/components/accordion/demos/cardlist/accordion-cardlist.component.ts
  libs/documentation/src/lib/components/accordion/demos/cardlist/accordion-cardlist.module.ts
Labels: Documentation

#670 Add documentation for npm link to readme
  README.md
Labels: Documentation

#672 Git 671 sds toast issue
  libs/documentation/src/lib/components/toasts/demos/basic/toasts-basic.component.ts
  libs/packages/components/src/lib/toast/toast-single.component.html
  libs/packages/components/src/lib/toast/toast.module.ts
Labels: bugfix

#673 Set page default to true when retreiving history from url
  libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.spec.ts
  libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
Labels: bugfix

#674 Update version to v10.0.21
  libs/packages/components/package.json
  libs/packages/experimental/package.json
  libs/packages/layouts/package.json
  libs/packages/sam-formly/package.json
  libs/packages/sam-material-extensions/package.json
  package-lock.json
  package.json
Labels: Release

#678 Delay loading of video source when preload is none
  libs/packages/components/src/lib/video-player/video-player.component.html
  libs/packages/components/src/lib/video-player/video-player.component.ts
Labels: bugfix

#680 Update default model comparison to treat 'true' / 'false' string as boolean values
  libs/documentation/src/lib/pages/layout/layout.component.html
  libs/documentation/src/lib/pages/layout/layout.component.ts
  libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
  libs/packages/sam-formly/src/lib/formly/types/multicheckbox.html
  libs/packages/sam-formly/src/lib/formly/types/multicheckbox.ts
Labels: bugfix

#686 Search layout display loading on search
  libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.html
  libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
Labels: bugfix

#695 Video player mobile issue
  libs/packages/components/src/lib/video-player/video-player.component.ts
Labels: bugfix

#697 Add aria label input for sidenavigation component
  libs/documentation/src/lib/components/sidenavigation/demos/optional/sidenavigation-optional.component.html
  libs/packages/components/src/lib/side-navigation/side-navigation.component.html
  libs/packages/components/src/lib/side-navigation/side-navigation.component.ts
Labels: bugfix

#698 Update app module for stackblitz template
  misc/stackblitzes-templates/app.module.ejs
Labels: Documentation
