Repository GSA/sam-design-system, pull requests merged in 2021-03, with the labels that each got.

#600 external-link demo
  libs/documentation/src/lib/components/external-link/demos/basic/external-link-basic.component.html
Labels: Documentation

#601 update card expand/collapse toggle for responsive layout
  libs/documentation/src/lib/pages/layout/layout-responsive/layout-responsive.component.html
  libs/documentation/src/lib/pages/layout/layout-responsive/layout-responsive.component.ts
Labels: bugfix

#602 added Hide icon to the external link
  libs/packages/layouts/src/lib/feature/footer/footer.component.html
  libs/packages/layouts/src/lib/feature/footer/model/FooterModel.ts
Labels: bugfix

#604 Update placeholder in demo
  libs/documentation/src/lib/components/autocomplete/demos/aria-label/autocomplete-aria-label.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/basic/autocomplete-basic.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/customtemplate/autocomplete-customtemplate.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/disable/autocomplete-disable.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/freetext/autocomplete-freetext.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/group/autocomplete-group.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/inputreadonly/autocomplete-inputreadonly.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/mincharacter/autocomplete-mincharacter.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/selectgroup/autocomplete-selectgroup.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/tagmode/autocomplete-tagmode.component.ts
  libs/documentation/src/lib/components/filters/demos/hideexpression/filters-hideexpression.component.ts
  libs/documentation/src/lib/components/filters/demos/optional/filters-optional.component.ts
  libs/documentation/src/lib/components/formly-autocomplete/demos/disable/autocomplete-disable.component.ts
  libs/documentation/src/lib/components/formly-autocomplete/demos/freetext/autocomplete-freetext.component.ts
  libs/documentation/src/lib/components/formly-autocomplete/demos/mincharacter/autocomplete-mincharacter.component.ts
  libs/documentation/src/lib/components/formly-autocomplete/demos/tag/autocomplete-tag.component.ts
  libs/documentation/src/lib/components/formly-autocomplete/demos/validation/autocomplete-validation.component.ts
  libs/documentation/src/lib/components/formly-datepicker/demos/basic/datepicker-basic.component.ts
  libs/documentation/src/lib/components/formly-datepicker/demos/daterange/datepicker-daterange.component.ts
  libs/documentation/src/lib/components/formly-datepicker/demos/validation/datepicker-validation.component.ts
  libs/documentation/src/lib/components/formly-readonly/demos/basic/readonly-basic.component.ts
  libs/documentation/src/lib/components/formly-readonly/demos/formlytype/readonly-formly-type.component.ts
  libs/documentation/src/lib/components/formly-search/demos/basic/search-basic.component.ts
  libs/documentation/src/lib/components/formly-search/demos/optional/search-optional.component.ts
  libs/documentation/src/lib/components/formly-search/demos/submit/search-handle-submit.component.ts
  libs/documentation/src/lib/components/search/demos/basic/search-basic.component.ts
  libs/documentation/src/lib/components/search/demos/optional/search-optional.component.ts
  libs/documentation/src/lib/pages/layout/filter.service.ts
  libs/packages/components/src/lib/search/search.component.html
  libs/packages/sam-formly/src/lib/formly/formly.config.ts
  libs/packages/sam-formly/src/lib/formly/types/datepicker.ts
  libs/packages/sam-formly/src/lib/formly/types/daterangepicker.ts
  libs/packages/sam-formly/src/lib/formly/types/textarea.ts
Labels: bugfix

#607 Update sds filters to allow users to pass in default model
  libs/documentation/src/lib/components/filters/demos/defaultValues/filters-default-value.component.html
  libs/documentation/src/lib/components/filters/demos/defaultValues/filters-default-value.component.ts
  libs/documentation/src/lib/components/filters/demos/defaultValues/filters-default-value.module.ts
  libs/documentation/src/lib/components/filters/filters.module.ts
  libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.html
  libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.spec.ts
  libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
  libs/packages/sam-formly/src/lib/formly-reset/formly-reset.component.ts
Labels: bugfix

#611 Add described by aria label to radio group form
  libs/packages/sam-formly/src/lib/formly/types/radio.ts
  libs/packages/sam-formly/src/lib/formly/wrappers/description.wrapper.ts
Labels: bugfix

#613 Add output event when an alert is dismissed
  libs/documentation/src/lib/components/system-alerts/demos/multiple/system-alerts-multiple.component.html
  libs/documentation/src/lib/components/system-alerts/demos/multiple/system-alerts-multiple.component.ts
  libs/documentation/src/lib/components/system-alerts/demos/single/system-alerts-single.component.html
  libs/documentation/src/lib/components/system-alerts/demos/single/system-alerts-single.component.ts
  libs/packages/layouts/src/lib/feature/system-alert/system-alert.component.ts
Labels: enhancement

#614 Remove aria-label default from autocomplete-search-configuration
  libs/packages/components/src/lib/autocomplete-search/models/SDSAutocompleteConfiguration.ts
Labels: bugfix

#617 Multiple fixes for responsive sidenav during prototype integration
  libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
  libs/packages/layouts/src/lib/feature/side-toolbar/side-toolbar.component.ts
  libs/packages/sam-formly/src/lib/formly-filters/service/sds-filter-model-update.service.ts
  libs/packages/sam-formly/src/lib/formly-filters/service/sds-filters-comunication.service.ts
Labels: bugfix

#616 IAE-47531: Add Slideout
  apps/sam-design-system-site/src/app/app.component.html
  libs/documentation/src/lib/components/slide-out/demos/basic/slide-out-basic.component.html
  libs/documentation/src/lib/components/slide-out/demos/basic/slide-out-basic.component.scss
  libs/documentation/src/lib/components/slide-out/demos/basic/slide-out-basic.component.ts
  libs/documentation/src/lib/components/slide-out/demos/basic/slide-out-basic.module.ts
  libs/documentation/src/lib/components/slide-out/demos/basic/slide-out-template.html
  libs/documentation/src/lib/components/slide-out/demos/basic/slide-out-template.scss
  libs/documentation/src/lib/components/slide-out/demos/template-ref/slide-out-template-ref.component.html
  libs/documentation/src/lib/components/slide-out/demos/template-ref/slide-out-template-ref.component.ts
  libs/documentation/src/lib/components/slide-out/demos/template-ref/slide-out-template-ref.module.ts
  libs/documentation/src/lib/components/slide-out/slide-out.module.ts
  libs/documentation/src/lib/documentation.module.ts
  libs/packages/components/src/lib/dialog/dialog-animations.ts
  libs/packages/components/src/lib/dialog/dialog-config.ts
  libs/packages/components/src/lib/dialog/dialog-container.component.ts
  libs/packages/components/src/lib/dialog/dialog-ref.ts
  libs/packages/components/src/lib/dialog/dialog.module.ts
  libs/packages/components/src/lib/dialog/dialog.ts
  package-lock.json
  package.json
Labels: enhancement

#626 Update github issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Documentation

#627 Fix typo on side toolbar logic change
  libs/packages/layouts/src/lib/feature/side-toolbar/side-toolbar.component.ts
Labels: breaking

#631 Add cross origin input option for video player
  libs/packages/components/src/lib/video-player/video-player.component.html
  libs/packages/components/src/lib/video-player/video-player.component.ts
Labels: bugfix

#634 Search icon alignment chnages
  libs/packages/components/src/lib/search/search.component.html
  libs/packages/components/src/lib/search/search.component.scss
  package-lock.json
Labels: bugfix

#637 Update min height of accordion
  libs/packages/sam-material-extensions/src/lib/accordion/accordion.component.scss
Labels: bugfix

#643 Hideoptional should not display optional label for daterange picker
  libs/documentation/src/lib/components/formly-datepicker/demos/daterange/datepicker-daterange.component.ts
  libs/packages/sam-formly/src/lib/formly/formly.config.ts
Labels: bugfix

#640 Add 'eg' on all placeholder text
  libs/documentation/src/lib/components/accordionwrapper/demos/basic/accordionwrapper-basic.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/aria-label/autocomplete-aria-label.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/basic/autocomplete-basic.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/customtemplate/autocomplete-customtemplate.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/disable/autocomplete-disable.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/freetext/autocomplete-freetext.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/group/autocomplete-group.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/inputreadonly/autocomplete-inputreadonly.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/mincharacter/autocomplete-mincharacter.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/selectgroup/autocomplete-selectgroup.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/tagmode/autocomplete-tagmode.component.ts
  libs/documentation/src/lib/components/descriptionwrapper/demos/basic/descriptionwrapper-basic.component.ts
  libs/documentation/src/lib/components/dialog/demos/overview/dialog-overview.component.html
  libs/documentation/src/lib/components/download/demos/formlymodal/formly-modal.component.ts
  libs/documentation/src/lib/components/filters/demos/defaultValues/filters-default-value.component.ts
  libs/documentation/src/lib/components/filters/demos/group-panel/filters-group-panel.component.ts
  libs/documentation/src/lib/components/filters/demos/optional/filters-optional.component.ts
  libs/documentation/src/lib/components/filterwrapper/demos/basic/filterwrapper-basic.component.ts
  libs/documentation/src/lib/components/form-field/demos/basic/form-field-basic.component.ts
  libs/documentation/src/lib/components/formly-autocomplete/demos/basic/autocomplete-basic.component.ts
  libs/documentation/src/lib/components/formly-autocomplete/demos/disable/autocomplete-disable.component.ts
  libs/documentation/src/lib/components/formly-autocomplete/demos/freetext/autocomplete-freetext.component.ts
  libs/documentation/src/lib/components/formly-autocomplete/demos/mincharacter/autocomplete-mincharacter.component.ts
  libs/documentation/src/lib/components/formly-autocomplete/demos/tag/autocomplete-tag.component.ts
  libs/documentation/src/lib/components/formly-autocomplete/demos/validation/autocomplete-validation.component.ts
  libs/documentation/src/lib/components/formly-datepicker/demos/basic/datepicker-basic.component.ts
  libs/documentation/src/lib/components/formly-datepicker/demos/daterange/datepicker-daterange.component.ts
  libs/documentation/src/lib/components/formly-datepicker/demos/validation/datepicker-validation.component.ts
  libs/documentation/src/lib/components/formly-input/demos/basic/input-basic.component.ts
  libs/documentation/src/lib/components/formly-readonly/demos/basic/readonly-basic.component.ts
  libs/documentation/src/lib/components/formly-search/demos/basic/search-basic.component.ts
  libs/documentation/src/lib/components/formly-search/demos/optional/search-optional.component.ts
  libs/documentation/src/lib/components/formly-search/demos/submit/search-handle-submit.component.ts
  libs/documentation/src/lib/components/formly-textarea/demos/basic/textarea-basic.component.ts
  libs/documentation/src/lib/components/groupwrappers/demos/accordion/group-accordion.component.ts
  libs/documentation/src/lib/components/groupwrappers/demos/panel/group-panel.component.ts
  libs/documentation/src/lib/components/labelwrapper/demos/basic/labelwrapper-basic.component.ts
  libs/documentation/src/lib/components/search/demos/basic/search-basic.component.ts
  libs/documentation/src/lib/components/search/demos/optional/search-optional.component.ts
  libs/documentation/src/lib/components/sidenavigation/demos/optional/sidenavigation-optional.component.ts
  libs/documentation/src/lib/components/templateoptions/demos/basic/templateoptions-basic.component.ts
  libs/documentation/src/lib/components/text/demos/basic/text-basic.component.ts
  libs/documentation/src/lib/components/validationwrapper/demos/basic/validationwrapper-basic.component.ts
  libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.spec.ts
  libs/packages/sam-formly/src/lib/formly/formly.config.ts
Labels: Documentation

#648 Updated version to 10.0.17
  libs/packages/components/package.json
  libs/packages/experimental/package.json
  libs/packages/layouts/package.json
  libs/packages/sam-formly/package.json
  libs/packages/sam-material-extensions/package.json
  package-lock.json
  package.json
Labels: Release

#647 Default template for default filter model changes for search-layout
  libs/documentation/src/lib/pages/layout/layout.component.html
  libs/documentation/src/lib/pages/layout/layout.component.ts
  libs/packages/components/src/lib/search-result-list/search-result-list.component.html
  libs/packages/components/src/lib/search-result-list/search-result-list.component.ts
  libs/packages/layouts/package.json
  libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.html
  libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
Labels: enhancement

#649 Move hideoptional method into exported function for date range picker
  libs/packages/sam-formly/src/lib/formly/formly.config.ts
Labels: bugfix

#651 Resolve height issue for accordion in ie
  libs/packages/sam-material-extensions/src/lib/accordion/accordion.component.scss
Labels: bugfix

#652 10.0.18
  libs/packages/components/package.json
  libs/packages/experimental/package.json
  libs/packages/layouts/package.json
  libs/packages/sam-formly/package.json
  libs/packages/sam-material-extensions/package.json
  package-lock.json
  package.json
Labels: Release

#653 Add dialog config option for side toolbar
  libs/documentation/src/lib/pages/layout/layout-responsive/layout-responsive.component.html
  libs/documentation/src/lib/pages/layout/layout-responsive/layout-responsive.component.ts
  libs/packages/components/src/lib/public-api.ts
  libs/packages/layouts/src/lib/feature/side-toolbar/side-toolbar.component.ts
Labels: bugfix
