Repository GSA/sam-design-system, pull requests merged in 2021-02, with the labels that each got.

#539 Resolve datepicker accordion autoclose and onChange not firing
  libs/packages/sam-formly/src/lib/formly/types/datepicker.ts
  libs/packages/sam-formly/src/lib/formly/types/daterangepicker.ts
  libs/packages/sam-formly/src/lib/formly/wrappers/group.wrapper.ts
Labels: bugfix

#543 Resolve jaws issues in autocomplete and selection panel
  libs/documentation/src/lib/components/collapse/demos/basic/collapse-basic.component.html
  libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html
  libs/packages/components/src/lib/selection-panel/selection-panel.component.html
Labels: bugfix

#548 IAE-46051: Remove style causing issue
  libs/packages/layouts/src/lib/feature/subheader/subheader.component.scss
Labels: bugfix

#545 Resolve outstanding 508 defects reported by entity team
  libs/packages/layouts/src/lib/feature/footer/footer.component.html
  libs/packages/layouts/src/lib/feature/header/header.component.html
  libs/packages/layouts/src/lib/feature/sds-feedback/sds-feedback.component.html
Labels: bugfix

#547 Refactoring external link directory
  libs/packages/components/src/lib/external-link/external-link.directive.ts
Labels: enhancement

#549 remove default queryparams handling
  libs/packages/components/src/lib/side-navigation/side-navigation.component.html
Labels: bugfix

#551 External link demo
  apps/sam-design-system-site/src/app/app.component.html
  libs/documentation/src/lib/apidoc/components/components.ts
  libs/documentation/src/lib/apidoc/components/documentation.json
  libs/documentation/src/lib/apidoc/formly/documentation.json
  libs/documentation/src/lib/apidoc/formly/formly.ts
  libs/documentation/src/lib/apidoc/layouts/documentation.json
  libs/documentation/src/lib/apidoc/layouts/layouts.ts
  libs/documentation/src/lib/components/external-link/demos/basic/external-link-basic.component.html
  libs/documentation/src/lib/components/external-link/demos/basic/external-link-basic.component.ts
  libs/documentation/src/lib/components/external-link/demos/basic/external-link-basic.module.ts
  libs/documentation/src/lib/components/external-link/external-link.module.ts
  libs/documentation/src/lib/documentation.module.ts
  libs/documentation/src/lib/pages/overview/overview.module.ts
  libs/packages/components/src/lib/external-link/external-link.module.ts
  libs/packages/layouts/src/lib/feature/footer/footer.module.ts
Labels: breaking

#550 Resolve failing unit tests
  libs/packages/components/src/lib/accordion/accordion-item.component.spec.ts
  libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.spec.ts
  libs/packages/components/src/lib/external-link/external-link.directive.spec.ts
  libs/packages/components/src/lib/selection-panel/selection-panel.component.spec.ts
  libs/packages/components/src/lib/toast/toast-single.component.html
  libs/packages/components/src/lib/toast/toast-single.component.ts
  libs/packages/components/src/lib/toast/toast-single.spec.ts
  libs/packages/components/src/lib/toast/toast.module.ts
  libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.spec.ts
  libs/packages/layouts/src/lib/feature/system-alert/system-alert.component.html
  libs/packages/layouts/src/lib/feature/system-alert/system-alert.component.spec.ts
  libs/packages/sam-material-extensions/src/lib/accordion/accordion.component.spec.ts
  libs/packages/sam-material-extensions/src/lib/button-group/button-group.component.spec.ts
  libs/packages/sam-material-extensions/src/lib/table/table-basic.component.spec.ts
  libs/packages/sam-material-extensions/src/lib/table/table.component.html
  libs/packages/sam-material-extensions/src/lib/table/table.module.ts
Labels: Documentation

#552 Release 10.0.9
  libs/packages/components/package.json
  libs/packages/experimental/package.json
  libs/packages/layouts/package.json
  libs/packages/sam-formly/package.json
  libs/packages/sam-material-extensions/package.json
  package-lock.json
  package.json
Labels: Release

#553 Autocomplete build fix
  libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html
  package-lock.json
  package.json
Labels: bugfix

#557 Side nav demo updated
  libs/documentation/src/lib/components/sidenavigation/demos/optional/sidenavigation-optional.component.html
Labels: Documentation

#559 Removing sds-filter demos
  libs/documentation/src/lib/components/filters/demos/basic/filters-basic.component.html
  libs/documentation/src/lib/components/filters/demos/basic/filters-basic.component.ts
  libs/documentation/src/lib/components/filters/demos/basic/filters-basic.module.ts
  libs/documentation/src/lib/components/filters/demos/config/fields.ts
  libs/documentation/src/lib/components/filters/demos/config/filter-config.component.html
  libs/documentation/src/lib/components/filters/demos/config/filter-config.component.ts
  libs/documentation/src/lib/components/filters/demos/config/filter-config.module.ts
  libs/documentation/src/lib/components/filters/filters.module.ts
Labels: Documentation

#556 Add aria live regions for new search results
  libs/packages/components/src/lib/pagination/pagination.component.html
  libs/packages/components/src/lib/search-result-list/search-result-list.component.html
Labels: bugfix

#555 IAE-45482: Tooltip/Popover refactor
  apps/sam-design-system-site/src/app/app.component.html
  libs/documentation/src/lib/components/popup/demos/basic/popup-basic.component.html
  libs/documentation/src/lib/components/tooltip-popover/demos/basic/popup-basic.component.html
  libs/documentation/src/lib/components/tooltip-popover/demos/basic/popup-basic.component.scss
  libs/documentation/src/lib/components/tooltip-popover/demos/basic/popup-basic.component.ts
  libs/documentation/src/lib/components/tooltip-popover/demos/basic/popup-basic.module.ts
  libs/documentation/src/lib/components/tooltip-popover/demos/tooltip/tooltip-basic.component.html
  libs/documentation/src/lib/components/tooltip-popover/demos/tooltip/tooltip-basic.component.ts
  libs/documentation/src/lib/components/tooltip-popover/demos/tooltip/tooltip-basic.module.ts
  libs/documentation/src/lib/components/tooltip-popover/tooltip-popover.module.ts
  libs/documentation/src/lib/documentation.module.ts
  libs/packages/components/src/lib/popover/debounce.decorator.ts
  libs/packages/components/src/lib/popover/popover.directive.ts
  libs/packages/components/src/lib/popover/popover.module.ts
  libs/packages/components/src/lib/public-api.ts
  libs/packages/components/src/lib/tooltip/tooltip.directive.ts
  libs/packages/components/src/lib/tooltip/tooltip.module.ts
  package-lock.json
Labels: enhancement

#562 Use provided labelText as default for autocomplete
  libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html
Labels: enhancement

#561 Update sds-filters to adjust for hideexpression configs
  libs/packages/sam-formly/src/lib/formly-filters/sds-filters.component.ts
Labels: bugfix

#563 Resolve issue with different radio groups in same field group being treated as one
  libs/packages/sam-formly/src/lib/formly/types/radio.ts
Labels: bugfix

#554 Update accordion styling
  libs/packages/sam-material-extensions/src/lib/accordion/accordion.component.html
  libs/packages/sam-material-extensions/src/lib/accordion/accordion.component.scss
Labels: bugfix

#565 Update logic in retreiving generated stackblitz files
  libs/documentation/src/lib/components/shared/examples-page/demo.component.ts
Labels: Documentation

#567 external link to include FSD link
  libs/documentation/src/lib/components/footer/demos/basic/footer-basic.component.ts
  libs/packages/components/src/lib/external-link/external-link.directive.ts
Labels: bugfix

#568 Updated search results to include custom template
  libs/documentation/src/lib/components/result-list/demos/basic/result-list-basic.component.html
  libs/documentation/src/lib/components/result-list/demos/basic/result-list-basic.component.ts
  libs/packages/components/src/lib/search-result-list/model/search-results.model.ts
  libs/packages/components/src/lib/search-result-list/search-result-list.component.html
  libs/packages/components/src/lib/search-result-list/search-result-list.component.ts
Labels: enhancement

#573 Remove default aria-label on autocomplete model
  libs/packages/components/src/lib/autocomplete/models/SDSAutocompletelConfiguration.model.ts
  libs/packages/sam-formly/src/lib/formly/types/radio.ts
Labels: bugfix

#576 IAE-47071: Add Roadmap page
  apps/sam-design-system-site/src/app/app.component.html
  libs/documentation/src/lib/documentation.module.ts
  libs/documentation/src/lib/pages/roadmap/roadmap.component.html
  libs/documentation/src/lib/pages/roadmap/roadmap.component.scss
  libs/documentation/src/lib/pages/roadmap/roadmap.component.ts
  libs/documentation/src/lib/pages/roadmap/roadmap.module.ts
  package-lock.json
  package.json
Labels: enhancement

#572 circleci should run all unit tests
  .circleci/config.yml
  package.json
Labels: Documentation

#580 Apply fix for accordions auto-closing on date validation error
  libs/packages/sam-formly/src/lib/formly/wrappers/form-field.accordian.ts
Labels: bugfix

#582 Add option to disable api call in layout component and update responsive layout demo
  libs/documentation/src/lib/pages/layout/data.service.ts
  libs/documentation/src/lib/pages/layout/layout-responsive/layout-responsive.component.html
  libs/documentation/src/lib/pages/layout/layout-responsive/layout-responsive.component.ts
  libs/packages/layouts/src/lib/feature/search-list-layout/model/search-list-layout.model.ts
  libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
  libs/packages/sam-formly/src/lib/formly-filters/service/sds-filters-comunication.service.spec.ts
  libs/packages/sam-formly/src/lib/formly-filters/service/sds-filters-comunication.service.ts
Labels: enhancement

#589 Modal dialog demo updates
  libs/documentation/src/lib/components/dialog/demos/alert/alert-template.html
  libs/documentation/src/lib/components/dialog/demos/alert/dialog-alert.component.html
  libs/documentation/src/lib/components/dialog/demos/alert/dialog-alert.component.ts
  libs/documentation/src/lib/components/dialog/demos/alert/dialog-alert.module.ts
  libs/documentation/src/lib/components/dialog/demos/basic/dialog-basic.component.html
  libs/documentation/src/lib/components/dialog/demos/basic/dialog-basic.component.ts
  libs/documentation/src/lib/components/dialog/demos/nested/dialog-nested.component.html
  libs/documentation/src/lib/components/dialog/demos/nested/dialog-nested.component.ts
  libs/documentation/src/lib/components/dialog/demos/nested/dialog-nested.module.ts
  libs/documentation/src/lib/components/dialog/demos/nested/overview-template.html
  libs/documentation/src/lib/components/dialog/demos/official/dialog-official.component.html
  libs/documentation/src/lib/components/dialog/demos/official/dialog-official.component.ts
  libs/documentation/src/lib/components/dialog/demos/official/dialog-official.module.ts
  libs/documentation/src/lib/components/dialog/demos/official/official-template.html
  libs/documentation/src/lib/components/dialog/demos/official/overview-template.html
  libs/documentation/src/lib/components/dialog/demos/overview/dialog-overview.component.html
  libs/documentation/src/lib/components/dialog/demos/overview/dialog-overview.component.ts
  libs/documentation/src/lib/components/dialog/demos/overview/dialog-overview.module.ts
  libs/documentation/src/lib/components/dialog/demos/overview/overview-template.html
  libs/documentation/src/lib/components/dialog/dialog.module.ts
Labels: Documentation

#583 Git 574 radio issue and 508 video fix
  libs/packages/components/src/lib/video-player/css/px-video.css
  libs/packages/components/src/lib/video-player/video-player.component.ts
  libs/packages/sam-formly/src/lib/formly/formly.module.ts
  libs/packages/sam-formly/src/lib/formly/types/radio.spec.ts
  libs/packages/sam-formly/src/lib/formly/types/radio.ts
Labels: bugfix

#584 Add aria label for external links
  libs/packages/components/src/lib/external-link/external-link.directive.spec.ts
  libs/packages/components/src/lib/external-link/external-link.directive.ts
Labels: bugfix

#590 Autocomplete demos updated
  libs/documentation/src/lib/components/autocomplete/autocomplete.module.ts
  libs/documentation/src/lib/components/autocomplete/demos/basic/autocomplete-basic.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/customtemplate/autocomplete-customtemplate.component.html
  libs/documentation/src/lib/components/autocomplete/demos/customtemplate/autocomplete-customtemplate.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/customtemplate/autocomplete-customtemplate.module.ts
  libs/documentation/src/lib/components/autocomplete/demos/disable/autocomplete-disable.component.html
  libs/documentation/src/lib/components/autocomplete/demos/disable/autocomplete-disable.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/disable/autocomplete-disable.module.ts
  libs/documentation/src/lib/components/autocomplete/demos/freetext/autocomplete-freetext.component.html
  libs/documentation/src/lib/components/autocomplete/demos/freetext/autocomplete-freetext.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/freetext/autocomplete-freetext.module.ts
  libs/documentation/src/lib/components/autocomplete/demos/inputreadonly/autocomplete-inputreadonly.component.html
  libs/documentation/src/lib/components/autocomplete/demos/inputreadonly/autocomplete-inputreadonly.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/inputreadonly/autocomplete-inputreadonly.module.ts
  libs/documentation/src/lib/components/autocomplete/demos/mincharacter/autocomplete-mincharacter.component.html
  libs/documentation/src/lib/components/autocomplete/demos/mincharacter/autocomplete-mincharacter.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/mincharacter/autocomplete-mincharacter.module.ts
  libs/documentation/src/lib/components/autocomplete/demos/optional/autocomplete-optional.component.html
  libs/documentation/src/lib/components/autocomplete/demos/optional/autocomplete-optional.component.scss
  libs/documentation/src/lib/components/autocomplete/demos/optional/autocomplete-optional.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/optional/autocomplete-optional.module.ts
  libs/documentation/src/lib/components/autocomplete/demos/optional/autocomplete-sample.data.ts
  libs/documentation/src/lib/components/autocomplete/demos/optional/autocomplete-sample.service.ts
  libs/documentation/src/lib/components/autocomplete/demos/services/autocomplete-sample.data.ts
  libs/documentation/src/lib/components/autocomplete/demos/services/autocomplete-sample.service.ts
  libs/documentation/src/lib/components/autocomplete/demos/tagmode/autocomplete-tagmode.component.html
  libs/documentation/src/lib/components/autocomplete/demos/tagmode/autocomplete-tagmode.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/tagmode/autocomplete-tagmode.module.ts
Labels: Documentation

#596 Update pagination input to include total pages
  libs/packages/components/src/lib/pagination/pagination.component.html
  libs/packages/layouts/src/lib/feature/actions-menu/actions-menu.component.html
Labels: bugfix

#599 Update stackblitz generate script, add autocomplete demo with aria la…
  libs/documentation/src/lib/components/autocomplete/autocomplete.module.ts
  libs/documentation/src/lib/components/autocomplete/demos/aria-label/autocomplete-aria-label.component.html
  libs/documentation/src/lib/components/autocomplete/demos/aria-label/autocomplete-aria-label.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/aria-label/autocomplete-aria-label.module.ts
  misc/generate-stackblitzes.ts
Labels: Documentation
