Repository GSA/sam-design-system, pull requests merged in 2021-01, with the labels that each got.

#475 IAE-44214 Add updateOn inheritance documentation
  libs/documentation/src/lib/components/templateoptions/demos/update-on-inheritance/update-on-inheritance.component.html
  libs/documentation/src/lib/components/templateoptions/demos/update-on-inheritance/update-on-inheritance.component.ts
  libs/documentation/src/lib/components/templateoptions/demos/update-on-inheritance/update-on-inheritance.module.ts
  libs/documentation/src/lib/components/templateoptions/templateoptions.module.ts
Labels: enhancement

#473 Update feedback on footer
  libs/documentation/src/lib/components/footer/demos/basic/footer-basic.component.html
  libs/documentation/src/lib/components/footer/demos/basic/footer-basic.module.ts
  libs/packages/layouts/src/lib/feature/footer/footer.component.html
  libs/packages/layouts/src/lib/feature/footer/footer.component.spec.ts
  libs/packages/layouts/src/lib/feature/footer/footer.component.ts
  libs/packages/layouts/src/lib/feature/footer/footer.module.ts
  libs/packages/layouts/src/lib/feature/footer/model/FooterModel.ts
  libs/packages/layouts/src/lib/feature/sds-feedback/sds-feedback.component.html
  libs/packages/layouts/src/lib/feature/sds-feedback/sds-feedback.component.scss
  libs/packages/layouts/src/lib/feature/sds-feedback/sds-feedback.component.spec.ts
  libs/packages/layouts/src/lib/feature/sds-feedback/sds-feedback.component.ts
  libs/packages/layouts/src/lib/feature/sds-feedback/sds-feedback.module.ts
  libs/packages/layouts/src/lib/public-api.ts
  package-lock.json
  package.json
Labels: breaking, enhancement

#486 updated export form sds-feedback component
  libs/packages/layouts/src/lib/public-api.ts
Labels: bugfix

#487 Git-469 Resolve documentation code markup issue
  apps/sam-design-system-site/src/app/app.module.ts
  apps/sam-design-system-site/src/app/app.routes.ts
  package-lock.json
  package.json
Labels: bugfix

#488 Add bug report and feature request templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Documentation

#491 Update header demo to use word notifications
  libs/documentation/src/lib/components/header/demos/basic/header-basic.component.ts
  libs/documentation/src/lib/components/header/demos/header-alerts/header-alerts.component.ts
  libs/documentation/src/lib/components/header/demos/header-hidden-logo/header-hidden-logo.component.ts
Labels: bugfix

#496 Resolve issue with autocomplete disable, unsubscribe on layout during onDestroy
  libs/packages/components/src/lib/autocomplete/autocomplete.component.ts
  libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
Labels: bugfix

#495 Add documentation section for stacking icons
  libs/documentation/src/lib/components/icons/demos/stacking/icons-stacking.component.html
  libs/documentation/src/lib/components/icons/demos/stacking/icons-stacking.component.ts
  libs/documentation/src/lib/components/icons/demos/stacking/icons-stacking.module.ts
  libs/documentation/src/lib/components/icons/icons.module.ts
  libs/packages/components/src/lib/icon/icon.component.scss
Labels: enhancement

#504 File Info Document title update
  libs/documentation/src/lib/components/formly/fileinfo/fileinfo.module.ts
  package-lock.json
Labels: Documentation

#506 Multi checkbox object values for IE fix
  libs/packages/sam-formly/src/lib/formly/types/multicheckbox.ts
Labels: bugfix

#508 Update route navigation url in result list
  libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
Labels: bugfix

#509 Add optional parameter to merge queryparam in sidenav
  libs/packages/components/src/lib/side-navigation/model/side-navigation-model.ts
  libs/packages/components/src/lib/side-navigation/side-navigation.component.html
  libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
Labels: enhancement

#512 Removed placeholder option
  libs/packages/components/src/lib/search/search.component.html
Labels: bugfix

#514 Remove onpush change detection strategy
  libs/packages/sam-material-extensions/src/lib/accordion/accordion.component.ts
Labels: bugfix

#513 Autocomplete formly 508 fixes
  libs/documentation/src/lib/components/autocomplete/demos/basic/autocomplete-basic.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/group/autocomplete-group.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/optional/autocomplete-optional.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/selectgroup/autocomplete-selectgroup.component.ts
  libs/documentation/src/lib/components/formly-autocomplete/demos/basic/autocomplete-basic.component.ts
  libs/documentation/src/lib/components/formly-autocomplete/demos/disable/autocomplete-disable.component.ts
  libs/documentation/src/lib/components/formly-autocomplete/demos/freetext/autocomplete-freetext.component.ts
  libs/documentation/src/lib/components/formly-autocomplete/demos/mincharacter/autocomplete-mincharacter.component.ts
  libs/documentation/src/lib/components/formly-autocomplete/demos/readonly/autocomplete-readonly.component.ts
  libs/documentation/src/lib/components/formly-autocomplete/demos/tag/autocomplete-tag.component.ts
  libs/documentation/src/lib/components/formly-autocomplete/demos/validation/autocomplete-validation.component.ts
  libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html
  libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.ts
Labels: bugfix

#515 Search-results-initial-template
  libs/packages/components/src/lib/search-result-list/search-result-list.component.ts
Labels: bugfix

#511 autocomplete-close icon changes for IE
  libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.html
  libs/packages/components/src/lib/autocomplete-search/autocomplete-search.component.scss
  libs/packages/components/src/lib/search/search.component.ts
  package-lock.json
Labels: bugfix

#516 Add prod build options for material extensions
  libs/packages/sam-material-extensions/tsconfig.lib.prod.json
Labels: Documentation

#517 update pagination demo and add flex display for datepicker with toggle
  libs/documentation/src/lib/components/table/demos/full/full.component.html
  libs/documentation/src/lib/components/table/demos/pagination/pagination.component.html
  libs/packages/sam-formly/src/lib/formly/types/datepicker.ts
  libs/packages/sam-formly/src/lib/formly/types/daterangepicker.ts
Labels: bugfix

#518 Multiple accessibility fixes on documentation site using access assistant
  apps/sam-design-system-site/src/app/app.component.html
  libs/documentation/src/lib/components/autocomplete/demos/basic/autocomplete-basic.component.html
  libs/documentation/src/lib/components/autocomplete/demos/group/autocomplete-group.component.html
  libs/documentation/src/lib/components/autocomplete/demos/optional/autocomplete-optional.component.html
  libs/documentation/src/lib/components/autocomplete/demos/optional/autocomplete-optional.component.ts
  libs/documentation/src/lib/components/autocomplete/demos/selectgroup/autocomplete-selectgroup.component.html
  libs/documentation/src/lib/components/dialog/demos/basic/dialog-basic.component.html
  libs/documentation/src/lib/components/filters/demos/config/fields.ts
  libs/documentation/src/lib/components/search/demos/basic/search-basic.component.ts
  libs/documentation/src/lib/components/search/demos/optional/search-optional.component.ts
  libs/documentation/src/lib/components/shared/examples-page/demo.component.html
  libs/documentation/src/lib/components/video/closing.md
  libs/documentation/src/lib/components/video/demos/basic/video-player-sample-data.ts
  libs/documentation/src/lib/shared/component-wrapper/component-wrapper.component.html
  libs/packages/components/src/lib/accordion/accordion-item-header.component.html
  libs/packages/components/src/lib/search/search.component.html
  libs/packages/components/src/lib/search/search.component.ts
  libs/packages/components/src/lib/toast/toast-single.component.html
  libs/packages/components/src/lib/video-player/video-player.component.html
  libs/packages/components/src/lib/video-player/video-player.ts
  libs/packages/sam-formly/src/lib/formly/types/multicheckbox.html
Labels: bugfix

#520 Update write valuelogic of autocomplete to accept duplicate updates
  libs/packages/components/src/lib/autocomplete/autocomplete.component.ts
Labels: bugfix

#521 Access Assistant checks on sam formly and layouts library
  libs/documentation/src/lib/components/formly-search/demos/basic/search-basic.component.ts
  libs/documentation/src/lib/components/formly-search/demos/optional/search-optional.component.ts
  libs/documentation/src/lib/components/formly-search/demos/submit/search-handle-submit.component.ts
  libs/documentation/src/lib/components/icons/demos/basic/icons-basic.component.html
  libs/documentation/src/lib/components/icons/demos/bootstrap/icons-bootstrap.component.html
  libs/documentation/src/lib/components/subheader/demos/search/subheader-search.component.ts
  libs/documentation/src/lib/components/subheader/demos/subpages/subheader-search-sub-pages.component.ts
  libs/documentation/src/lib/components/subheader/demos/workspace/subheader-tier-2-workspace.component.ts
  libs/documentation/src/lib/pages/layout/layout-responsive/layout-responsive.component.html
  libs/documentation/src/lib/pages/layout/layout.component.html
  libs/packages/components/src/lib/text/text.component.ts
  libs/packages/layouts/src/lib/feature/footer/footer.component.html
  libs/packages/layouts/src/lib/feature/header/header.component.html
  libs/packages/layouts/src/lib/feature/system-alert/system-alert.component.html
  libs/packages/sam-formly/src/lib/formly/types/multicheckbox.html
  libs/packages/sam-formly/src/lib/formly/types/text.ts
Labels: bugfix

#525 Group wrapper replaced with new accordion
  libs/documentation/src/lib/pages/layout/filter.service.ts
  libs/packages/sam-formly/src/lib/formly/formly.config.ts
  libs/packages/sam-formly/src/lib/formly/formly.module.ts
  libs/packages/sam-formly/src/lib/formly/wrappers/custom-wrapper.ts
  libs/packages/sam-formly/src/lib/formly/wrappers/form-field.accordian.ts
  libs/packages/sam-formly/src/lib/formly/wrappers/group.wrapper.ts
  libs/packages/sam-material-extensions/src/lib/accordion/accordion.component.html
  libs/packages/sam-material-extensions/src/lib/accordion/accordion.component.scss
  libs/packages/sam-material-extensions/src/lib/accordion/accordion.component.ts
Labels: bugfix

#529 Update focus issues on popup and fileinfo
  libs/documentation/src/lib/components/popup/demos/basic/popup-basic.component.html
  libs/packages/sam-formly/src/lib/formly/types/fileinfo.ts
Labels: bugfix

#532 Add default value option for layout component
  libs/documentation/src/lib/pages/layout/layout.component.ts
  libs/packages/layouts/src/lib/feature/search-list-layout/model/search-list-layout.model.ts
  libs/packages/layouts/src/lib/feature/search-list-layout/search-list-layout.component.ts
Labels: enhancement

#537 Remove borders in table for material calendar in datepickers
  libs/packages/sam-formly/src/lib/formly/types/datepicker.ts
Labels: bugfix
